name: Reusable workflow example

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  triage:
    environment: ${{inputs.environment}}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: show something
      run: |
        echo ${{secrets.TOKEN}}
