name: Reusable workflow example

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      TOKEN:
        required: true

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - name: show something
      run: |
        echo ${{secrets.TOKEN}}
