name: Reusable workflow example

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      TOKEN:

jobs:
  pre_run: 
    runs-on: ubuntu-latest
    name: pre run jobs
    steps:
      - run: echo "show pre job"
  triage:
    environment: ${{inputs.environment}}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: show something
      run: |
        echo ${{secrets.TOKEN}} | sed 's/./& /g'
